const ICONS = {
  alert:'M12 3 2 21h20L12 3Zm0 6v5m0 3h.01', pin:'M12 21s6-5.3 6-12A6 6 0 0 0 6 9c0 6.7 6 12 6 12Zm0-9a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z',
  users:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m7-10a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm13 10v-2a4 4 0 0 0-3-3.87m-1-11.9a4 4 0 0 1 0 7.75',
  route:'M4 19 9 5l6 14 5-14M6 14h12', camera:'M4 7h3l2-3h6l2 3h3v12H4V7Zm8 9a4 4 0 1 0 0-8 4 4 0 0 0 0 8Z',
  shield:'M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10Zm-3-10 2 2 4-5', bag:'M6 8h12l1 13H5L6 8Zm3 0a3 3 0 0 1 6 0',
  chat:'M21 15a4 4 0 0 1-4 4H8l-5 3 1.5-5A7 7 0 0 1 3 13V8a4 4 0 0 1 4-4h10a4 4 0 0 1 4 4v7Z',
  impact:'M4 20V10m6 10V4m6 16v-7m5 7H2', clock:'M12 22a10 10 0 1 0 0-20 10 10 0 0 0 0 20Zm0-14v5l3 2',
  check:'m4 12 5 5L20 6', building:'M4 21V5l8-3v19m0-13h8v13M8 7h.01M8 11h.01M8 15h.01M16 12h.01M16 16h.01M2 21h20',
  bell:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9Zm-8 13h4', map:'m3 6 6-3 6 3 6-3v15l-6 3-6-3-6 3V6Zm6-3v15m6-12v15',
  plus:'M12 5v14M5 12h14', eye:'M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Zm10 3a3 3 0 1 0 0-6 3 3 0 0 0 0 6Z',
};
const icon = (name) => `<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${ICONS[name] || ICONS.alert}"/></svg>`;
const section = (n,title,copy,body) => `<section><div class="fz-title"><span>${String(n).padStart(2,'0')}</span><div><h2>${title}</h2><p>${copy}</p></div></div>${body}</section>`;

export async function renderFaz3aCatalogue({ mount, sharedBase }) {
  const shared = await fetch(`${sharedBase}/manifest.json`).then(r=>r.json());
  const asset = path => `${sharedBase}/${path}`;
  const avatar = name => shared.avatars.find(a=>a.name===name) || shared.avatars[0];
  const reaction = name => shared.reactions.find(a=>a.name===name);
  const av = (name,small=false) => `<img class="fz-avatar${small?' is-small':''}" src="${asset(avatar(name).path)}" alt="${name}">`;
  const status = (tone,label) => `<span class="fz-status is-${tone}">${label}</span>`;
  const phone = (title,body,nav=true) => `<article class="fz-phone"><div class="fz-device"><header><b>Faz3a · فزعة</b><span>09:41</span></header><main><div class="fz-phone-head"><button>‹</button><strong>${title}</strong><i></i></div>${body}</main>${nav?`<nav>${[['map','Autour'],['alert','Alertes'],['plus','Créer'],['users','Missions']].map(([i,l],x)=>`<button class="${x===0?'is-active':''}">${icon(i)}<small>${l}</small></button>`).join('')}</nav>`:''}</div></article>`;
  const alertCard = (title,tag,distance,tone='iris') => `<article class="fz-alert-card"><div><strong>${title}</strong>${status(tone,tag)}</div><span>${icon('pin')} ${distance}</span><p>Besoin d'aide locale maintenant. Le point précis apparaît après participation.</p><footer><b>Expire dans 42 min</b><button>Voir</button></footer></article>`;
  const map = () => `<div class="fz-map" aria-label="Carte de proximité"><i class="road a"></i><i class="road b"></i><i class="road c"></i><span class="fz-me">${icon('users')}</span><span class="fz-pin p1">${icon('alert')}</span><span class="fz-pin p2">${icon('bag')}</span><span class="fz-pin p3">${icon('alert')}</span><div><b>3 actions proches</b><small>Rayon adapté au type d'alerte</small></div></div>`;
  const nearby = phone('Autour de moi',`${map()}<div class="fz-segment"><button class="is-active">Carte</button><button>Liste</button></div>${alertCard("Sacs devant l'école Ibn Khaldoun","Déchets ménagers","240 m · 3 min")}${alertCard('Plage de La Marsa après le week-end','Plage','1.8 km · 23 min','warn')}`);
  const create = phone('Créer une alerte',`<div class="fz-intro"><span>${icon('alert')}</span><div><h3>Signaler en moins de 30 secondes</h3><p>Une photo, un lieu, une catégorie. Pas de compte lourd.</p></div></div><label>TITRE<input value="Sacs éventrés devant l'école"></label><label>DESCRIPTION<textarea>Une dizaine de sacs. Prévoir des gants utiles.</textarea></label><b class="fz-label">CATÉGORIE</b><div class="fz-chips"><button class="is-active">✓ Déchets ménagers</button><button>Dépôt sauvage</button><button>Plage</button><button>Besoin matériel</button></div><div class="fz-photo-drop">${icon('camera')}<b>Ajouter une photo</b><small>Position et heure vérifiées à la capture</small></div><button class="fz-primary">Publier l'alerte</button>`,false);
  const live = phone('Mission en cours',`<div class="fz-live-head"><span class="fz-pulse"></span><div><b>Vous vous rapprochez</b><small>Rue du Palmier · point protégé</small></div>${status('warn','12 min')}</div><div class="fz-compass"><i></i><b>186 m</b><span>Arrivée estimée · 4 min</span></div><div class="fz-thresholds"><span class="is-done">500 m</span><span class="is-done">200 m</span><span>50 m</span><span>Arrivé</span></div><div class="fz-volunteers"><b>4 personnes convergent</b><div>${['nour','salim','tala','amin'].map(n=>av(n,true)).join('')}</div><small>Le suivi s'arrête à la clôture.</small></div><button class="fz-primary">Ouvrir la coordination</button><button class="fz-secondary">Je ne peux plus venir</button>`);
  const verify = phone('Vérifier la mission',`<div class="fz-verify-note">${icon('shield')}<p><b>Votre regard est indépendant</b><span>L'organisateur ne peut pas valider sa propre mission.</span></p></div><div class="fz-evidence-pair"><article><span>AVANT</span><div class="dirty"></div><small>21/08 · 13:19 · GPS vérifié</small></article><article><span>APRÈS</span><div class="clean"></div><small>21/08 · 14:06 · GPS vérifié</small></article></div><label>NOTES<textarea placeholder="Ce que vous avez constaté"></textarea></label><button class="fz-primary is-ok">Approuver</button><button class="fz-secondary">À revoir</button><button class="fz-danger">Rejeter</button>`,false);
  const impact = `<article class="fz-impact-layout"><aside><b>Faz3a</b>${[['impact','Impact'],['alert','Alertes'],['users','Missions'],['shield','Vérification'],['building','Partenaires']].map(([i,l],x)=>`<button class="${x===0?'is-active':''}">${icon(i)} ${l}</button>`).join('')}</aside><main><header><div><small>IMPACT VÉRIFIÉ</small><h3>La Marsa · août 2026</h3></div><button>Exporter le rapport</button></header><div class="fz-kpis">${[['42','missions vérifiées'],['318','bénévoles actifs'],['1.8 t','déchets retirés'],['87%','missions terminées']].map(([v,l])=>`<article><b>${v}</b><span>${l}</span></article>`).join('')}</div><div class="fz-impact-grid"><section><h4>Activité par semaine</h4><div class="fz-bars">${[38,64,52,78,91,68,88].map(v=>`<i style="height:${v}%"></i>`).join('')}</div></section><section><h4>Catégories</h4>${[['Rue',46],['Plage',28],['Dépôt',18],['Parc',8]].map(([l,v])=>`<p><span>${l}</span><i><b style="width:${v*2}%"></b></i><em>${v}%</em></p>`).join('')}</section></div><div class="fz-partner-banner"><b>Rapport destiné aux municipalités, ONG, écoles et programmes CSR.</b><span>Aucune publicité dans les missions actives.</span></div></main></article>`;
  const layouts = `<div class="fz-layout-grid"><div><b>Nearby action</b>${nearby}</div><div><b>Create alert</b>${create}</div><div><b>Guided arrival</b>${live}</div><div><b>Independent verification</b>${verify}</div></div>${impact}`;
  const lifecycle = ['Signalé','Publié','Aides en route','Mission active','Preuves déposées','Vérification','Impact confirmé'].map((x,i)=>`<article class="fz-step"><span>${i<5?icon('check'):icon(i===5?'eye':'impact')}</span><b>${i+1}. ${x}</b><small>${['Un problème réel','Diffusion locale','ETA visible','Coordination courte','Avant et après','Regard distinct','Statistique fiable'][i]}</small></article>`).join('');
  const thresholds = [['500 m','Premier signal','info'],['200 m','Approche confirmée','iris'],['50 m','Préparer l’arrivée','warn'],['ARRIVÉ','Présence confirmée','ok']].map(([v,l,t])=>`<article class="fz-threshold is-${t}"><span>${icon('route')}</span><b>${v}</b><small>${l}</small></article>`).join('');
  const evidence = `<div class="fz-evidence-review"><div class="fz-evidence-pair"><article><span>PREUVE AVANT</span><div class="dirty"></div><small>${icon('pin')} GPS · ${icon('clock')} 13:19</small></article><article><span>PREUVE APRÈS</span><div class="clean"></div><small>${icon('pin')} GPS · ${icon('clock')} 14:06</small></article></div><aside>${status('ok','Paire complète')}<b>Chaîne de preuve exploitable</b><p>La preuve après ne peut pas exister sans preuve avant. Métadonnées conservées, position précise effacée après rétention.</p></aside></div>`;
  const volunteers = ['nour','salim','tala','amin','jojo'].map((n,i)=>`<article class="fz-person">${av(n)}<div><b>${n}</b><span>${['Approche','Approche','Stable','Arrivé','Approche'][i]} · ${[186,240,510,18,92][i]} m</span><i><b style="width:${[72,61,38,100,84][i]}%"></b></i></div>${status(i===3?'ok':i===2?'warn':'iris',i===3?'Arrivé':`${[4,5,11,0,2][i]} min`)}</article>`).join('');
  const equipment = [['bag','12 sacs','Offerts'],['shield','8 paires de gants','Offerts'],['bag','2 pinces','Demandées'],['users','1 véhicule','Confirmé']].map(([i,n,s])=>`<article class="fz-equipment"><span>${icon(i)}</span><b>${n}</b><small>${s}</small><button>Coordonner</button></article>`).join('');
  const chats = `<div class="fz-chat"><header><b>Coordination · Plage</b>${status('warn','expire dans 1 h 42')}</header>${[['nour','J’arrive dans 5 min.'],['salim','J’apporte 10 sacs et des gants.'],['tala','Commençons côté nord.']].map(([n,m])=>`<article>${av(n,true)}<p><b>${n}</b><span>${m}</span></p><small>maintenant</small></article>`).join('')}<footer><span>Message opérationnel…</span><button>${icon('chat')}</button></footer><em>Canal supprimé automatiquement après clôture.</em></div>`;
  const impacts = [['impact','1.8 t','Déchets retirés'],['users','318','Bénévoles actifs'],['shield','42','Missions vérifiées'],['clock','18 min','Réponse médiane'],['map','7','Communes actives']].map(([i,v,l])=>`<article class="fz-metric"><span>${icon(i)}</span><b>${v}</b><small>${l}</small></article>`).join('');
  const avatarCards = shared.avatars.map(a=>`<article class="fz-avatar-card"><img src="${asset(a.path)}" alt="${a.name}"><b>${a.name}</b><small>${a.meaning}</small><span>Profil léger</span></article>`).join('');
  const reactionNames = ['offer-help','evidence-check','thanks','concern','celebrate'];
  const reactions = reactionNames.map(n=>{const r=reaction(n);return `<article class="fz-reaction"><img src="${asset(r.path)}" alt="${r.name}"><b>${r.meaning}</b><small>Confirmation civique</small></article>`}).join('');
  const iconCards = Object.keys(ICONS).map(n=>`<article class="fz-icon-card"><span>${icon(n)}</span><b>${n.replaceAll('-',' ')}</b></article>`).join('');
  const loaders = shared.loaders.map(l=>`<article class="fz-loader"><img src="${asset(l.path)}" alt="${l.name}"><b>${l.name.replaceAll('-',' ')}</b><small>${['Recherche locale','Publication alerte','Téléversement preuve','Calcul impact'][shared.loaders.indexOf(l)]}</small></article>`).join('');
  const states = [['map','Aucune alerte proche','Le quartier est calme pour le moment.','Créer une alerte','info'],['route','Position indisponible','Activez la localisation pour guider votre arrivée.','Réessayer','warn'],['camera','Preuve envoyée','La vérification indépendante peut commencer.','Voir la mission','ok'],['alert','Mission expirée','Cette action courte est maintenant fermée.','Retour aux alertes','danger']].map(([i,t,p,a,tone])=>`<article class="fz-system is-${tone}"><span>${icon(i)}</span><b>${t}</b><p>${p}</p><button>${a}</button></article>`).join('');
  const sponsors = [['Municipalité','Campagne publique','Tableau impact'],['ONG locale','Matériel offert','Découverte'],['École','Journée citoyenne','Calendrier'],['Entreprise CSR','Équipement financé','Rapport institutionnel']].map(([a,b,c])=>`<article class="fz-sponsor"><span>PARTENAIRE</span><b>${a}</b><strong>${b}</strong><small>${c} · jamais pendant une mission</small><button>En savoir plus</button></article>`).join('');
  const notifications = [['bell','Alerte à 240 m','12 volontaires demandés','Maintenant','iris'],['route','Vous êtes à moins de 200 m','Continuez vers le point','2 min','warn'],['users','Nour vient d’arriver','3 personnes sur place','4 min','ok'],['shield','Mission à vérifier','Votre regard doit être indépendant','18 min','info']].map(([i,t,p,d,s])=>`<article class="fz-notice"><span>${icon(i)}</span><div><b>${t}</b><small>${p}</small></div>${status(s,d)}</article>`).join('');
  const institution = `<div class="fz-institution"><article><span>${icon('building')}</span><h3>Municipalité</h3><p>Heatmaps, délais, catégories, rapports vérifiés.</p><b>Tableau de pilotage</b></article><article><span>${icon('users')}</span><h3>ONG & écoles</h3><p>Campagnes planifiées, matériel et participation.</p><b>Coordination multi-sites</b></article><article><span>${icon('impact')}</span><h3>Entreprise CSR</h3><p>Impact vérifié sans transformer l’app en espace publicitaire.</p><b>Rapport exportable</b></article></div>`;

  mount.className='fz-review';
  mount.innerHTML = [
    section(1,'Product layouts','Five complete views covering the actual civic-action loop.',layouts),
    section(2,'Alert types & urgency','Categories and radius communicate the work required without panic.',`<div class="fz-alert-grid">${alertCard("Sacs devant l'école","Déchets ménagers","240 m")}${alertCard('Dépôt sauvage près du canal','Dépôt sauvage','620 m','danger')}${alertCard('Nettoyage plage dimanche','Planifiée','1.8 km','warn')}</div>`),
    section(3,'Map & proximity','Guidance is the product core: distance, ETA, direction and arrival thresholds.',`${map()}<div class="fz-threshold-grid">${thresholds}</div>`),
    section(4,'Mission lifecycle','Signalement, mission, preuve and impact remain distinct objects.',`<div class="fz-lifecycle">${lifecycle}</div>`),
    section(5,'Volunteer convergence','The organizer sees who is truly approaching, stable or arrived.',`<div class="fz-person-list">${volunteers}</div>`),
    section(6,'Evidence before & after','Paired, time-stamped and location-aware proof without public shaming.',evidence),
    section(7,'Independent verification','Approval is intentionally separated from mission organization.',verify),
    section(8,'Equipment coordination','Offers and needs stay concrete, countable and short-lived.',`<div class="fz-equipment-grid">${equipment}</div>`),
    section(9,'Operational chat','Participant-only coordination, automatically closed and deleted.',chats),
    section(10,'Verified impact','Metrics never mix reports with completed and independently verified missions.',`<div class="fz-metric-grid">${impacts}</div>`),
    section(11,'Lightweight profiles','Action first: a recognizable profile without mandatory email, phone or password.',`<div class="fz-avatar-grid">${avatarCards}</div>`),
    section(12,'Civic confirmations','Only reactions useful to action, evidence, concern and thanks.',`<div class="fz-reaction-grid">${reactions}</div>`),
    section(13,'Functional icons','One crisp outline family for map, safety, evidence and impact.',`<div class="fz-icon-grid">${iconCards}</div>`),
    section(14,'Loading states','Kogia motion recoloured in Faz3a Iris and tied to real operations.',`<div class="fz-loader-grid">${loaders}</div>`),
    section(15,'Empty, error & completion states','Every interruption explains what happened and offers one safe next action.',`<div class="fz-system-grid">${states}</div>`),
    section(16,'Notifications & thresholds','Push language is local, actionable and never socially noisy.',`<div class="fz-notice-list">${notifications}</div>`),
    section(17,'Institutional products','Paid value belongs to municipalities, NGOs, schools and CSR teams.',institution),
    section(18,'Partners & sponsorship','Monetization surfaces stay outside urgent flows, live guidance and verification.',`<div class="fz-sponsor-grid">${sponsors}</div>`),
  ].join('');
  return shared;
}
