const title = (value) => value.replaceAll("-", " ");

const NAV_ITEMS = [
  ["online", "Play"], ["hint", "Puzzles"], ["teacher", "Learn"], ["history", "Watch"],
  ["leaderboard", "Stats"], ["friends", "Community"], ["achievement", "Events"], ["settings", "Settings"],
];

const BOARD_STATES = {
  placement: { a:[0,2,6,8,10,14,16,20,28,34], d:[1,5,7,9,12,15,19,29,33,35], label:"Placement" },
  ready: { a:Array.from({length:49},(_,i)=>i).filter((i)=>i!==24&&i%2===0), d:Array.from({length:49},(_,i)=>i).filter((i)=>i!==24&&i%2===1), label:"Board ready" },
  opening: { a:[2,6,8,14,20,24,28,34,42], d:[1,7,9,12,19,29,35,41,47], selected:[24], label:"Open the middle" },
  capture: { a:[8,15,22,24,30,36,38], d:[9,16,23,29,31,37], selected:[24], danger:[23], route:[17,10], label:"Enclosure" },
  exchange: { a:[2,8,12,18,30,38,43], d:[5,10,20,27,34,41,46], selected:[41], route:[8,12], label:"Exchange" },
};

const AD_SLOTS = [
  ["Leaderboard", "970 × 90", "Above the game shell"],
  ["Right rail", "300 × 600", "Desktop play and analysis"],
  ["Rectangle", "300 × 250", "Dashboard and post-game"],
  ["In-feed", "728 × 90", "Between dashboard modules"],
  ["Sticky mobile", "320 × 100", "Bottom of mobile screens"],
  ["Sponsored card", "Native", "Between learning or event cards"],
];

export async function renderKharbgaCatalogue({ base, mount }) {
  const manifest = await fetch(`${base}/manifest.json`).then((response) => response.json());
  const url = (path) => `${base}/${path}`;
  const sprite = url("assets/svg/icons.svg?v=20260822-refined");
  const icon = (id, label = "") => `<svg aria-label="${label}"><use href="${sprite}#icon-${id}"></use></svg>`;
  const skin = manifest.skins.find((item) => item.id === manifest.defaultSkin);
  const profile = (name) => manifest.profiles.find((item) => item.name === name);

  const board = (stateName = "capture", compact = false) => {
    const state = BOARD_STATES[stateName];
    const cells = Array.from({ length:49 }, (_, index) => {
      const side = state.a.includes(index) ? "attacker" : state.d.includes(index) ? "defender" : "";
      const classes = [index === 24 ? "is-middle" : "", state.selected?.includes(index) ? "is-selected" : "", state.danger?.includes(index) ? "is-danger" : "", state.route?.includes(index) ? "is-route" : ""].filter(Boolean).join(" ");
      const piece = side ? `<img src="${url(skin[side])}" alt="${side} Soldier">` : "";
      return `<div class="khp-cell ${classes}" role="gridcell" aria-label="${index === 24 ? "salty middle house" : `house ${index + 1}`}">${piece}</div>`;
    }).join("");
    return `<div class="khp-board-wrap${compact ? " is-compact" : ""}"><div class="khp-board" role="grid" aria-label="7 by 7 Kharbga board">${cells}</div></div>`;
  };

  const playerBar = (name, role, time) => {
    const item = profile(name);
    return `<div class="khp-player"><img src="${url(item.path)}" alt="${item.name}"><span><strong>${item.name}</strong><small>${role} · 1,${role === "Attacker" ? "482" : "517"}</small></span><b>${time}</b></div>`;
  };

  const rail = (expanded = false) => `<nav class="khp-rail${expanded ? " is-expanded" : ""}" aria-label="Kharbga navigation"><div class="khp-brand">K</div>${NAV_ITEMS.map(([id,label],index)=>`<button class="${index===0?"is-active":""}">${icon(id,label)}<span>${label}</span></button>`).join("")}<i></i><button>${icon("invite","Invite")}<span>Invite</span></button></nav>`;

  const analysis = () => `<div class="khp-analysis"><div class="khp-tabs"><button class="is-active">Moves</button><button>Chat</button><button>Info</button><button>Rules</button></div><div class="khp-analysis-title"><span>${icon("capture")} Enclosure review</span><button>${icon("settings")}</button></div><ol>${[["1.","Place ×2","a4 · c2"],["2.","Open middle","d4 → d5"],["3.","Enclose","c5 × d5"],["4.","Continue","d5 × f5"],["5.","Exchange","1 protected : 2"]].map(([n,a,b],i)=>`<li class="${i===3?"is-current":""}"><b>${n}</b><span>${a}</span><em>${b}</em><small>${["2.1s","4.8s","7.2s","3.4s","—"][i]}</small></li>`).join("")}</ol><div class="khp-quality"><span>● 2 strong</span><span>● 1 missed</span><span>● 1 risky</span></div><div class="khp-playback"><button>${icon("restart")}</button><button>${icon("undo")}</button><button class="is-play">${icon("move")}</button><button>${icon("move")}</button><button>${icon("restart")}</button></div></div>`;

  const ad = (kind, size, copy = "Your campaign here") => `<aside class="khp-ad khp-ad-${kind}"><span>ADVERTISEMENT</span><strong>${copy}</strong><small>${size}</small><button>Ad choices</button></aside>`;

  const liveLayout = () => `<article class="khp-layout khp-live-layout"><div class="khp-app-shell">${rail()}<main><div class="khp-top-ad">${ad("leaderboard","970 × 90","Reach active players")}</div><div class="khp-game-grid"><section class="khp-game-stage">${playerBar("aliya","Defender","03:58")}${board("capture")}${playerBar("hamma","Attacker","03:08")}</section>${analysis()}${ad("rail","300 × 600","Desert stories. Modern play.")}</div></main></div><strong class="khp-layout-name">Desktop live play</strong></article>`;

  const quickLayout = () => `<article class="khp-layout"><div class="khp-app-shell khp-dashboard-shell">${rail()}<main><div class="khp-dashboard-head"><span><img src="${url(profile("naji").path)}" alt="">Welcome back, Naji</span><b>12-day table streak</b></div><div class="khp-dashboard"><section class="khp-start"><h3>Play Kharbga</h3><div class="khp-time-row"><button class="is-active">5 min</button><button>10 min</button><button>3 days</button></div><button class="khp-primary">Start game</button>${[["online","Play online"],["teacher","Play a guide"],["friends","Play a friend"],["achievement","Tournament"]].map(([id,label])=>`<button class="khp-menu-row">${icon(id)}<span>${label}</span><b>›</b></button>`).join("")}</section><section class="khp-dashboard-cards"><div>${board("opening",true)}<strong>Daily position</strong><button>Solve</button></div><div>${board("placement",true)}<strong>Learn placement</strong><button>Start lesson</button></div><div>${board("exchange",true)}<strong>Review last game</strong><button>Review</button></div></section>${ad("rail","300 × 600","Support Kharbga culture")}</div></main></div><strong class="khp-layout-name">Quick-play home</strong></article>`;

  const resultLayout = () => `<article class="khp-layout"><div class="khp-result-scene">${board("capture",true)}<div class="khp-result-modal"><button class="khp-close">×</button><span>TABLE COMPLETE</span><h3>Aliya wins</h3><p>Hamma has no legal route.</p><div class="khp-result-players"><img src="${url(profile("aliya").path)}" alt=""><b>+21</b><img src="${url(profile("hamma").path)}" alt=""></div><div class="khp-result-stats"><span><b>2</b>Strong</span><span><b>1</b>Missed</span><span><b>3</b>Captures</span></div><button class="khp-primary">Game review</button><div><button>New 5 min</button><button>Rematch</button></div>${ad("modal","300 × 100","Sponsored reward")}</div></div><strong class="khp-layout-name">Post-game result</strong></article>`;

  const mobileLayout = () => `<article class="khp-layout khp-mobile-card"><div class="khp-phone"><div class="khp-mobile-top"><b>Kharbga</b>${icon("settings")}</div>${playerBar("meriem","Defender","04:12")}${board("opening")}${playerBar("salah","Attacker","04:03")}<div class="khp-mobile-actions"><button>${icon("undo")}</button><button>${icon("chat")}</button><button>${icon("hint")}</button><button>${icon("settings")}</button></div>${ad("mobile","320 × 100","Mobile sponsor")}</div><strong class="khp-layout-name">Mobile live play</strong></article>`;

  const statStrip = () => `<div class="khp-stat-strip"><article><b>⚡ 1,482</b><small>Rapid table</small><i style="--score:72%"></i><span>+38 this week</span></article><article><b>◉ 1,375</b><small>Long table</small><i style="--score:58%"></i><span>12 games</span></article><article><b>◆ 1,144</b><small>Daily table</small><i style="--score:46%"></i><span>5 active</span></article></div>`;

  const historyRows = () => `<div class="khp-history-list">${[
    ["hamma","Victory","Enclosure · 5 min","+18"], ["meriem","Defeat","Exchange · 5 min","−7"],
    ["salah","Victory","No legal route · 10 min","+12"], ["aliya","Draw","Protected exchange · 10 min","+1"],
    ["ammar","Victory","Chain capture · Daily","+9"],
  ].map(([name,result,detail,score],index)=>`<article><span class="khp-history-kind">${index < 2 ? "⚡" : index < 4 ? "◉" : "◆"}</span><img src="${url(profile(name).path)}" alt="${name}"><span><strong>${name}</strong><small>${detail}</small></span><b class="is-${result.toLowerCase()}">${result}</b><em>${score}</em><button>Review</button></article>`).join("")}</div>`;

  const profileLayout = () => `<article class="khp-layout khp-profile-layout"><div class="khp-app-shell khp-ecosystem-shell">${rail()}<main>${ad("leaderboard","970 × 90","Play rooted. Think ahead.")}<section class="khp-profile-hero"><img src="${url(profile("naji").path)}" alt="Naji"><div><span class="khp-online-dot">ONLINE</span><h3>Naji El Haff</h3><p>Table player from Tozeur · Member since 2024</p><small>Desert routes, patient exchanges, strong finishes.</small></div><button>Edit profile</button></section><nav class="khp-profile-tabs"><button class="is-active">Overview</button><button>Games</button><button>Stats</button><button>Friends</button><button>Awards</button><button>Clubs</button></nav>${statStrip()}<div class="khp-profile-columns"><section><div class="khp-panel-head"><h4>Recent games</h4><button>View all</button></div>${historyRows()}</section><aside class="khp-progress-card"><span>${icon("history")}</span><div><b>37 day streak</b><small>Personal best · 52 days</small></div><i><b style="width:71%"></b></i><hr><span>${icon("achievement")}</span><div><b>Caravan League</b><small>11th place · top 18%</small></div></aside></div></main></div><strong class="khp-layout-name">Player profile ecosystem</strong></article>`;

  const historyLayout = () => `<article class="khp-layout khp-history-layout"><div class="khp-app-shell khp-ecosystem-shell">${rail()}<main><div class="khp-dashboard-head"><span>${icon("history")}<strong>Game history</strong><small>991 recorded tables</small></span><div class="khp-filter-row"><button class="is-active">All games</button><button>5 min</button><button>Daily</button><button>Filters</button></div></div>${statStrip()}<div class="khp-history-workspace"><section><div class="khp-history-columns"><span>TYPE</span><span>PLAYER / RESULT</span><span>OUTCOME</span><span>RATING</span><span></span></div>${historyRows()}</section><aside>${ad("rectangle","300 × 250","Master the next route")}<div class="khp-mini-summary"><b>August summary</b><span><strong>61%</strong> win rate</span><span><strong>23</strong> captures</span><span><strong>7</strong> streak</span></div></aside></div></main></div><strong class="khp-layout-name">History and performance</strong></article>`;

  const pieceCards = manifest.skins.flatMap((item) => [["Side A",item.attacker],["Side B",item.defender]].map(([side,path])=>`<article class="khp-asset-card"><span>${side}</span><img src="${url(path)}" alt="${item.name} ${side}"><strong>${item.name}</strong><small>Equal Soldier · same power</small></article>`)).join("");
  const avatars = manifest.profiles.map((item)=>`<article class="khp-avatar-card"><div><img src="${url(item.path)}" alt="${item.name}"><i></i></div><strong>${item.name}</strong><span>${item.title}</span><small>1,${120 + manifest.profiles.indexOf(item)*53}</small></article>`).join("");
  const reactions = manifest.reactions.map((item)=>`<article class="khp-reaction-card"><img src="${url(item.path)}" alt="${title(item.name)}"><strong>${title(item.name)}</strong><span><img src="${url(item.path)}" alt="">32 px</span></article>`).join("");
  const icons = manifest.functionalIcons.symbols.map((id)=>`<article class="khp-icon-card">${icon(id,title(id))}<strong>${title(id)}</strong></article>`).join("");
  const stateCards = Object.keys(BOARD_STATES).map((state)=>`<article class="khp-state-card">${board(state,true)}<strong>${BOARD_STATES[state].label}</strong></article>`).join("");
  const adCards = AD_SLOTS.map(([name,size,use])=>`<article>${ad(name.toLowerCase().replaceAll(" ","-"),size,name)}<strong>${name}</strong><p>${use}</p></article>`).join("");
  const leagueCards = [["history","37","Day streak","7 days to next ember"],["achievement","11th","Caravan League","Top 18% this season"],["move","1,482","Rapid table","Personal best 1,527"],["origins","24","Oasis points","Earned this week"]].map(([symbol,value,label,detail],index)=>`<article class="khp-league-card tone-${index+1}"><span>${icon(symbol)}</span><div><b>${value}</b><strong>${label}</strong><small>${detail}</small></div><i><b style="width:${[71,64,82,48][index]}%"></b></i></article>`).join("");
  const awardCards = [["achievement","First enclosure","Win by surrounding"],["capture","Chain keeper","Complete 3 captures"],["origins","Living rules","Study a regional variant"],["friends","Open table","Play 10 community games"],["leaderboard","Caravan climber","Reach the top league"],["history","Old roads","Review 25 games"]].map(([id,name,detail],index)=>`<article class="khp-award-card tone-${index%4+1}"><span>${icon(id)}</span><strong>${name}</strong><small>${detail}</small><b>${index < 4 ? "EARNED" : `${60-index*4}%`}</b></article>`).join("");
  const passportCards = [["Tunis","Medina tables","18"],["Tozeur","Oasis routes","12"],["Kairouan","Courtyard rules","9"],["Djerba","Island exchange","7"]].map(([place,style,total],index)=>`<article class="khp-passport-card"><div class="stamp-${index+1}">${icon("origins")}</div><strong>${place}</strong><small>${style}</small><b>${total} games</b></article>`).join("");

  mount.className = "kh-pro-review";
  mount.innerHTML = `
    <section><div class="khp-section-title"><span>01</span><div><h2>Layouts</h2><p>Six complete product layouts: play, start, result, mobile, profile and history.</p></div></div><div class="khp-layout-stack">${liveLayout()}${quickLayout()}${profileLayout()}${historyLayout()}<div class="khp-layout-pair">${resultLayout()}${mobileLayout()}</div></div></section>
    <section><div class="khp-section-title"><span>02</span><div><h2>Navigation & play menu</h2><p>Compact rail, expanded navigation, contextual play menu and useful secondary space.</p></div></div><div class="khp-nav-review">${rail()}${rail(true)}<div class="khp-play-menu"><h3>Play Kharbga</h3>${[["online","Play online","Matched by level"],["teacher","Play a guide","Learn at your pace"],["friends","Play a friend","Invite to your table"],["achievement","Tournaments","Community events"],["origins","Living rules","History and variants"]].map(([id,a,b])=>`<button>${icon(id)}<span><strong>${a}</strong><small>${b}</small></span><b>›</b></button>`).join("")}</div><aside class="khp-nav-context"><span class="khp-kicker">PLAYING NOW</span><b>4,208 tables</b><small>Players from 31 regions are online.</small><div><span>${icon("achievement")}</span><strong>Friday Oasis Cup</strong><small>Registration closes in 02:18:42</small><button class="khp-primary">View event</button></div>${ad("native","Native","Support living play")}</aside></div></section>
    <section><div class="khp-section-title"><span>03</span><div><h2>Boardgame states</h2><p>Five authentic Kharbga phases on one readable 7×7 visual system.</p></div></div><div class="khp-state-grid">${stateCards}</div></section>
    <section><div class="khp-section-title"><span>04</span><div><h2>Pieces</h2><p>Material Soldiers only—no chess hierarchy or borrowed silhouettes.</p></div></div><div class="khp-assets-grid">${pieceCards}</div></section>
    <section><div class="khp-section-title"><span>05</span><div><h2>Player avatars</h2><p>Community identity at profile, player-bar and presence sizes.</p></div></div><div class="khp-avatar-grid">${avatars}</div></section>
    <section><div class="khp-section-title"><span>06</span><div><h2>Reactions & emojis</h2><p>New compact reaction family designed for 32 px in-game use.</p></div></div><div class="khp-reaction-grid">${reactions}</div></section>
    <section><div class="khp-section-title"><span>07</span><div><h2>Functional icons</h2><p>Thirty-six controls for play, learning, community and moderation.</p></div></div><div class="khp-icon-grid">${icons}</div></section>
    <section><div class="khp-section-title"><span>08</span><div><h2>Game controls</h2><p>Timers, tabs, playback, actions and review controls.</p></div></div><div class="khp-controls-review">${playerBar("aliya","Defender","03:58")}<div class="khp-tabs"><button class="is-active">Moves</button><button>Chat</button><button>Info</button><button>Rules</button></div><div class="khp-playback"><button>${icon("restart")}</button><button>${icon("undo")}</button><button class="is-play">${icon("move")}</button><button>${icon("move")}</button><button>${icon("restart")}</button></div><div class="khp-action-row"><button class="khp-primary">Confirm move</button><button>Offer exchange</button><button>Resign</button></div></div></section>
    <section><div class="khp-section-title"><span>09</span><div><h2>Analysis & move history</h2><p>Kharbga phases and captures replace chess notation and openings.</p></div></div><div class="khp-analysis-review">${analysis()}${ad("rectangle","300 × 250","Review sponsor")}</div></section>
    <section><div class="khp-section-title"><span>10</span><div><h2>Match results</h2><p>Winner, reason, progress, review and rematch states.</p></div></div>${resultLayout()}</section>
    <section><div class="khp-section-title"><span>11</span><div><h2>Advertising layouts</h2><p>Reserved inventory with explicit dimensions; ads never cover the board or controls.</p></div></div><div class="khp-ad-grid">${adCards}</div><div class="khp-ad-map"><span>970×90 leaderboard</span><div><b>GAME / CONTENT</b><i>300×600 right rail</i></div><span>728×90 in-feed</span><span>320×100 mobile sticky</span></div></section>
    <section><div class="khp-section-title"><span>12</span><div><h2>Responsive layouts</h2><p>Desktop, tablet and mobile preserve the board before secondary panels and ads.</p></div></div><div class="khp-responsive-review"><article><b>Desktop</b><div class="desktop"><i></i><main></main><aside></aside><em>AD</em></div></article><article><b>Tablet</b><div class="tablet"><main></main><aside></aside><em>AD</em></div></article><article><b>Mobile</b><div class="mobile"><main></main><nav></nav><em>AD</em></div></article></div></section>
    <section><div class="khp-section-title"><span>13</span><div><h2>Player profile & social identity</h2><p>A sharp public identity with status, biography, tabs, performance and recent activity.</p></div></div>${profileLayout()}</section>
    <section><div class="khp-section-title"><span>14</span><div><h2>Ratings & performance</h2><p>Fast-scanning numerical hierarchy for every Kharbga time format.</p></div></div><div class="khp-performance-review">${statStrip()}<div class="khp-performance-detail"><article><span>WIN RATE</span><b>61.4%</b><small>+4.8% over 30 days</small></article><article><span>AVG. CAPTURES</span><b>3.7</b><small>Top 22% of players</small></article><article><span>BEST STREAK</span><b>9</b><small>Current streak: 4</small></article><article><span>TABLES PLAYED</span><b>991</b><small>Since January 2024</small></article></div></div></section>
    <section><div class="khp-section-title"><span>15</span><div><h2>Game history</h2><p>Dense but readable records with native Kharbga outcomes instead of chess notation.</p></div></div><div class="khp-history-review"><div class="khp-panel-head"><h4>Game history <small>991</small></h4><div class="khp-filter-row"><button class="is-active">All</button><button>Wins</button><button>5 min</button><button>Filters</button></div></div>${historyRows()}</div></section>
    <section><div class="khp-section-title"><span>16</span><div><h2>Streaks, leagues & progression</h2><p>Motivation without visual noise: one strong symbol, one number and one progress track.</p></div></div><div class="khp-league-grid">${leagueCards}</div></section>
    <section><div class="khp-section-title"><span>17</span><div><h2>Awards & achievements</h2><p>Achievements derived from real Kharbga actions, learning and community participation.</p></div></div><div class="khp-award-grid">${awardCards}</div></section>
    <section><div class="khp-section-title"><span>18</span><div><h2>Regional passports</h2><p>A culturally grounded collection system for regional table traditions—never national stereotypes.</p></div></div><div class="khp-passport-grid">${passportCards}</div></section>
    <section><div class="khp-section-title"><span>19</span><div><h2>Content, support & footer</h2><p>Secondary navigation stays quiet so the play experience remains dominant.</p></div></div><footer class="khp-footer"><div><strong>Kharbga</strong><span>Play</span><span>Learn</span><span>Community</span><span>Living rules</span><span>Support</span><span>Privacy</span></div><small>© 2026 Kogia Group · Kharbga is a living table-game tradition.</small><nav><button>العربية</button><button>FR</button><button>EN</button>${icon("friends")}${icon("chat")}</nav></footer></section>
    <section><div class="khp-section-title"><span>20</span><div><h2>Community, chat & notifications</h2><p>Useful social signals with restrained colour, clear authorship and moderation access.</p></div></div><div class="khp-social-review"><section><div class="khp-panel-head"><h4>Table chat</h4><button>${icon("settings")} Safety</button></div><div class="khp-chat-list"><article><img src="${url(profile("aliya").path)}" alt="Aliya"><p><b>Aliya</b><span>That enclosure was clean. Well played!</span><small>20:41</small></p></article><article><img src="${url(profile("hamma").path)}" alt="Hamma"><p><b>Hamma</b><span>I missed the second route 😄</span><small>20:42</small></p></article><article class="is-system">${icon("achievement")}<p><b>Table notice</b><span>Keep chat friendly and focused on play.</span></p></article></div><div class="khp-chat-compose"><button>${icon("chat")}</button><span>Write a message…</span><button>${icon("move")}</button></div></section><aside><article>${icon("friends")}<div><b>Aliya followed you</b><small>After your 5 min table · 2m</small></div><button>Follow back</button></article><article>${icon("achievement")}<div><b>Achievement unlocked</b><small>First enclosure · 18m</small></div><button>View</button></article><article>${icon("invite")}<div><b>Salah invited you</b><small>10 min table · now</small></div><button class="khp-primary">Join</button></article></aside></div></section>
    <section><div class="khp-section-title"><span>21</span><div><h2>Connection, empty & system states</h2><p>Every interruption explains what happened, protects the current table and offers one next action.</p></div></div><div class="khp-system-grid"><article><span class="khp-state-symbol is-loading">${icon("move")}</span><b>Finding a table</b><p>Looking for a player near your level.</p><small>Usually under 20 seconds</small></article><article><span class="khp-state-symbol is-warning">${icon("history")}</span><b>Reconnecting</b><p>Your table is protected while connection returns.</p><small>Attempt 2 of 5</small></article><article><span class="khp-state-symbol">${icon("history")}</span><b>No games yet</b><p>Completed tables and reviews will appear here.</p><button class="khp-primary">Play first game</button></article><article><span class="khp-state-symbol is-success">${icon("achievement")}</span><b>Back at the table</b><p>Connection restored. No moves were lost.</p><button>Continue</button></article></div></section>`;
  return manifest;
}
