const I={idea:'M9 18h6m-5 3h4M8 14c-2-1-3-3-3-5a7 7 0 0 1 14 0c0 2-1 4-3 5-1 1-1 2-1 2H9c0-1 0-1-1-2Z',article:'M6 3h9l4 4v14H6V3Zm8 0v5h5M9 12h6m-6 4h6',community:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2m3-10a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm13 10v-2a4 4 0 0 0-3-3.9',product:'M4 5h16v14H4V5Zm0 5h16M9 10v9',chart:'M4 20V10m6 10V4m6 16v-7m5 7H2',client:'M12 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8Zm-7 9a7 7 0 0 1 14 0',money:'M12 2v20m5-16H9a3 3 0 0 0 0 6h6a3 3 0 0 1 0 6H6',launch:'M5 19c-2 0-3-1-3-3 0-3 3-5 6-5 1-4 4-7 9-8 1 5-2 8-6 9 0 3-2 6-5 6Zm8-8 4 4M5 16l-2 5 5-2',settings:'M12 15a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm8-3 2-1-2-4-2 1-2-1-1-3h-5L9 7 7 8 5 7l-2 4 2 1v2l-2 1 2 4 2-1 2 1 1 3h5l1-3 2-1 2 1 2-4-2-1v-2Z',search:'M11 19a8 8 0 1 0 0-16 8 8 0 0 0 0 16Zm6-2 5 5',check:'m4 12 5 5L20 6',bell:'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9Zm-8 13h4'};
const icon=n=>`<svg viewBox="0 0 24 24"><path d="${I[n]||I.idea}"/></svg>`;
const sec=(n,t,p,b)=>`<section><div class="kgp-title"><span>${String(n).padStart(2,'0')}</span><div><h2>${t}</h2><p>${p}</p></div></div>${b}</section>`;
export async function renderGroupCatalogue({mount,sharedBase,brandBase}){
 const [shared,brand,products]=await Promise.all([fetch(`${sharedBase}/manifest.json`).then(r=>r.json()),fetch(`${brandBase}/marque/manifest.json`).then(r=>r.json()),fetch(`../manifests/assets.json`).then(r=>r.json())]);
 const a=p=>`${sharedBase}/${p}`,b=p=>`${brandBase}/${p}`;
 const nav=`<nav class="kgp-nav"><b>Kogia</b><span>Explorer</span><span>Produits</span><span>Communauté</span><span>À propos</span><i></i><button>Se connecter</button><button class="kgp-primary">Rejoindre</button></nav>`;
 const home=`<article class="kgp-page">${nav}<main><section class="kgp-hero"><small>KOGIA GROUP · TUNISIE</small><h3>Des idées qui méritent de remonter à la surface.</h3><p>Explorer sérieusement les opportunités, construire les solutions qui comptent, puis réunir les personnes capables de les faire vivre.</p><div><button class="kgp-primary">Explorer les idées</button><button>Découvrir les produits</button></div><div class="kgp-echo"><i></i><i></i><i></i><span>${icon('idea')}</span></div></section><section class="kgp-feature"><small>ARTICLE VEDETTE · 15 MIN</small><h4>Du sable à l'écran : le Kharbga peut-il devenir un grand jeu de stratégie numérique ?</h4><p>Problème, marché, risques, plan produit et verdict honnête.</p><button>Lire l'analyse →</button></section><section class="kgp-three">${[['idea','Découvrir','Une idée étudiée en profondeur.'],['community','Discuter','Les personnes concernées enrichissent le projet.'],['launch','Développer','Les idées utiles deviennent réelles.']].map(([i,t,p])=>`<article><span>${icon(i)}</span><b>${t}</b><p>${p}</p></article>`).join('')}</section></main></article>`;
 const directory=`<article class="kgp-page">${nav}<main><div class="kgp-pagehead"><div><small>ÉCOSYSTÈME KOGIA</small><h3>Produits et projets</h3><p>Un portefeuille honnête : en production, en construction ou en préparation.</p></div><button>Proposer un besoin</button></div><div class="kgp-product-grid">${[['coreon','Coreon EDU','Gestion scolaire','En production'],['faz3a','Faz3a','Action citoyenne','En construction'],['suite','Suite Kogia','Finance, CRM, RH','En préparation'],['kharbga','Kharbga','Jeu de stratégie vivant','Prototype']].map(([id,n,d,s])=>{let m=brand.marks.find(x=>x.lane===id);return `<article style="--lane:${products.products[id]?.accent600||m?.color}"><img src="${b(m.path)}" alt=""><span>${s}</span><h4>${n}</h4><p>${d}</p><button>Voir le projet →</button></article>`}).join('')}</div></main></article>`;
 const article=`<article class="kgp-page">${nav}<main class="kgp-reading"><header><small>TECHNOLOGIE · PROJET KOGIA · 15 MIN</small><h3>Une idée n'est pas un produit : le chemin de la curiosité à la preuve</h3><p>Une analyse pratique du problème, du marché, des risques et de la première expérience à construire.</p><div><span>OO</span><b>Othman Ounis</b><small>Publié le 22 août 2026</small></div></header><aside><b>Dans cette analyse</b><span>01 · Le problème réel</span><span>02 · Pour qui ?</span><span>03 · Modèle possible</span><span>04 · Risques</span><span>05 · Verdict Kogia</span></aside><section><h4>Le problème réel</h4><p>Une bonne idée commence par un problème observable, fréquent et coûteux. La technologie vient ensuite, jamais avant.</p><blockquote>Explorer profondément. Faire remonter seulement ce qui mérite d'exister.</blockquote><h4>Verdict Kogia</h4><div class="kgp-verdict"><b>À tester</b><span>Valeur claire · risque maîtrisable · prototype en 3 semaines</span></div></section></main></article>`;
 const consoleLayout=`<article class="kgp-console"><aside><b>Kogia Console</b>${[['chart','Vue groupe'],['product','Catalogue'],['client','Clients'],['money','Facturation'],['launch','Provisioning'],['settings','Réglages']].map(([i,l],x)=>`<button class="${x===0?'is-active':''}">${icon(i)} ${l}</button>`).join('')}</aside><main><header><div><small>CONSOLE PROPRIÉTAIRE</small><h3>Vue groupe</h3></div><button>Nouvelle organisation</button></header><div class="kgp-kpis">${[['€12.8k','MRR groupe','+8.4%'],['24','clients actifs','+3'],['7','produits suivis','stable'],['99.94%','services sains','30 jours']].map(([v,l,d])=>`<article><span>${l}</span><b>${v}</b><small>${d}</small></article>`).join('')}</div><div class="kgp-console-grid"><section><h4>Revenu par produit</h4><div class="kgp-bars">${[72,58,34,24,18,12].map((v,i)=>`<i style="height:${v}%;--c:${['#2547e8','#7539e4','#6c4de6','#0f766e','#c2410c','#36506f'][i]}"></i>`).join('')}</div></section><section><h4>État des services</h4>${[['Coreon EDU','Production','ok'],['Kogia Community','Production','ok'],['Faz3a API','Suspendu','warn'],['Suite demo','Actif','info']].map(([n,s,t])=>`<p><b>${n}</b><span class="is-${t}">${s}</span></p>`).join('')}</section></div></main></article>`;
 const layouts=`<div class="kgp-layouts"><div><b>Corporate home</b>${home}</div><div><b>Product directory</b>${directory}</div><div><b>Long-form idea analysis</b>${article}</div><div><b>Owner console</b>${consoleLayout}</div></div>`;
 const markCards=brand.marks.filter(m=>!['white','ink'].includes(m.lane)).map(m=>`<article class="kgp-mark" style="--lane:${m.color}"><img src="${b(m.path)}" alt="${m.name}"><b>${m.name}</b><span>${m.status}</span></article>`).join('');
 const productCards=brand.marks.filter(m=>['group','coreon','faz3a','kharbga','suite','soldeo','relio','cadreo','caissa','cargon','areneo','planeo','serveo','lumeon'].includes(m.lane)).map((m,i)=>`<article class="kgp-product" style="--lane:${m.color}"><img src="${b(m.path)}" alt=""><div><b>${m.name}</b><span>${['Groupe','Éducation','Civic tech','Jeu vivant','Plateforme','Finance','CRM','RH','POS','WMS','Réservations','Projets','Support','Intelligence'][i]}</span></div><small>${i<2?'EN PRODUCTION':i===2?'EN CONSTRUCTION':'EN PRÉPARATION'}</small></article>`).join('');
 const ideaCards=[['deep-dive','Problème','Qui souffre, combien, à quelle fréquence ?'],['hidden-opportunity','Opportunité','Pourquoi maintenant et pourquoi nous ?'],['revenue','Modèle','Qui paie et pour quelle valeur ?'],['evidence-check','Preuve','Quel test peut invalider nos hypothèses ?'],['concern','Risques',"Qu'est-ce qui peut tuer le projet ?"],['surface','Verdict','Construire, observer ou abandonner ?']].map(([i,t,p])=>`<article class="kgp-idea-card"><img src="${a((shared.icons.find(x=>x.name===i)||shared.icons[0]).path)}"><b>${t}</b><p>${p}</p></article>`).join('');
 const community=`<div class="kgp-community"><aside><b>Votre Kogia</b><button>${icon('article')} Fil</button><button>${icon('search')} Explorer</button><button>${icon('idea')} Écrire</button><button>${icon('community')} Communautés</button></aside><main><header><h3>Idées en discussion</h3><button class="kgp-primary">Publier une idée</button></header>${[['nour','Une coopérative numérique pour les artisans locaux','Business · 28 réactions'],['salim','Comment vérifier un projet civique sans bureaucratie ?','Technologie · 16 réactions'],['tala','Peut-on cartographier les opportunités invisibles ?','Recherche · 34 réactions']].map(([n,t,s])=>{let av=shared.avatars.find(x=>x.name===n);return `<article><img src="${a(av.path)}"><div><b>${t}</b><span>${s}</span><p>Une exploration structurée, des objections honnêtes et une prochaine étape concrète.</p></div><button>Suivre</button></article>`}).join('')}</main></div>`;
 const avatars=shared.avatars.map(x=>`<article class="kgp-avatar"><img src="${a(x.path)}"><b>${x.name}</b><small>${x.meaning}</small><span>Monde Kogia</span></article>`).join('');
 const reactions=shared.reactions.map(x=>`<article class="kgp-reaction"><img src="${a(x.path)}"><b>${x.meaning}</b><small>${x.name}</small></article>`).join('');
 const icons=shared.icons.map(x=>`<article class="kgp-icon"><img src="${a(x.path)}"><b>${x.name.replaceAll('-',' ')}</b></article>`).join('');
 const loaders=shared.loaders.map(x=>`<article class="kgp-loader"><img src="${a(x.path)}"><b>${x.name.replaceAll('-',' ')}</b><span>${['Recherche','Incubation idée','Synchronisation','Publication'][shared.loaders.indexOf(x)]}</span></article>`).join('');
 const pipeline=['Idée capturée','Analyse publiée','Discussion ouverte','Prototype décidé','Produit construit','Impact mesuré'].map((x,i)=>`<article><span>${i+1}</span><b>${x}</b><small>${['Signal brut','Problème, marché, risques','Connaissance communautaire','Verdict transparent','Équipe et livraison','Apprendre et améliorer'][i]}</small></article>`).join('');
 const clientRows=[['École Ennasr','Coreon EDU','Actif','€420'],['Atlas Conseil','Relio + Soldéo','Essai','€180'],['Municipalité La Marsa','Faz3a','Pilote','€0'],['Studio Nawa','Suite Kogia','Provisioning','€260']].map(([n,p,s,v])=>`<article><span>${n.slice(0,2).toUpperCase()}</span><div><b>${n}</b><small>${p}</small></div><em>${s}</em><strong>${v}</strong><button>Gérer</button></article>`).join('');
 const billing=`<div class="kgp-billing"><header><h3>Abonnements & revenu</h3><button>Créer un plan</button></header><div class="kgp-kpis"><article><span>MRR</span><b>€12,840</b><small>+8.4%</small></article><article><span>ARR projeté</span><b>€154k</b><small>12 mois</small></article><article><span>Essais</span><b>6</b><small>2 expirent bientôt</small></article><article><span>Impayés</span><b>€480</b><small>3 factures</small></article></div><div class="kgp-invoices">${[['KG-2041','École Ennasr','€420','Payé'],['KG-2040','Atlas Conseil','€180','En attente'],['KG-2039','Studio Nawa','€260','Payé']].map(r=>`<p>${r.map((x,i)=>`<span class="c${i}">${x}</span>`).join('')}</p>`).join('')}</div></div>`;
 const states=[['article','Aucun brouillon','Commencez par noter le problème observé.','Écrire une idée'],['product','Produit en préparation','La promesse est documentée, pas encore disponible.','Suivre les progrès'],['settings','Service indisponible','Les données restent protégées pendant la reprise.','Réessayer'],['check','Publication réussie',"L'analyse est visible par la communauté.","Voir l'article"]].map(([i,t,p,a])=>`<article class="kgp-state"><span>${icon(i)}</span><b>${t}</b><p>${p}</p><button>${a}</button></article>`).join('');
 const responsive=`<div class="kgp-responsive"><article><b>Corporate desktop</b><div class="desk"><nav></nav><main></main><aside></aside><footer></footer></div></article><article><b>Console tablet</b><div class="tablet"><nav></nav><main></main><aside></aside></div></article><article><b>Community mobile</b><div class="mobile"><main></main><nav></nav></div></article></div>`;
 mount.className='kgp-review';mount.innerHTML=[
 sec(1,'Corporate & product layouts','Four complete surfaces for company story, portfolio, analysis and operations.',layouts),
 sec(2,'Product marks','The whale geometry stays fixed; each product owns one approved or proposed lane colour.',`<div class="kgp-mark-grid">${markCards}</div>`),
 sec(3,'Portfolio directory','Product status is stated honestly and never implied by colour alone.',`<div class="kgp-product-list">${productCards}</div>`),
 sec(4,'Idea analysis framework','Every business article follows a useful, repeatable reasoning structure.',`<div class="kgp-idea-grid">${ideaCards}</div>`),
 sec(5,'Idea-to-product pipeline','The core Kogia story becomes a visible operating model.',`<div class="kgp-pipeline">${pipeline}</div>`),
 sec(6,'Community experience','Publishing and discussion support products without becoming a generic social network.',community),
 sec(7,'Kogia personalities','Universal whale characters represent different ways of thinking.',`<div class="kgp-avatar-grid">${avatars}</div>`),
 sec(8,'Community reactions','Stable semantic reactions for articles, objections, evidence and help.',`<div class="kgp-reaction-grid">${reactions}</div>`),
 sec(9,'Functional icons','Original Kogia metaphor icons connect exploration, ideas, solutions and products.',`<div class="kgp-icon-grid">${icons}</div>`),
 sec(10,'Loading & publishing states','Motion comes from echo, pearl and surfacing metaphors.',`<div class="kgp-loader-grid">${loaders}</div>`),
 sec(11,'Owner console','The company can operate its portfolio without exposing internal controls publicly.',consoleLayout),
 sec(12,'Clients & organizations','One consolidated lifecycle across products and plans.',`<div class="kgp-clients"><header><h3>Clients</h3><button>Nouvelle organisation</button></header>${clientRows}</div>`),
 sec(13,'Subscriptions & billing','Recurring revenue, trials and collection status use explicit wording.',billing),
 sec(14,'Provisioning','A purchased product becomes an owned workspace through a traceable sequence.',`<div class="kgp-provision">${['Commande confirmée','Organisation créée','Administrateur invité','Produit configuré','Domaine vérifié','Mise en service'].map((x,i)=>`<article><span>${i<4?icon('check'):icon('launch')}</span><b>${x}</b><small>${i<4?'Terminé':i===4?'En attente':'À venir'}</small></article>`).join('')}</div>`),
 sec(15,'Metrics & decision charts','Group totals stay neutral; product series use their lane colours.',consoleLayout),
 sec(16,'Empty, error & success states','Clear language and one next action on every non-happy path.',`<div class="kgp-state-grid">${states}</div>`),
 sec(17,'Responsive architecture','Public story, community and owner console adapt differently by task.',responsive),
 sec(18,'Calls to action & footer','A small action hierarchy keeps exploration primary and sales contextual.',`<div class="kgp-cta"><div><small>KOGIA COMMUNITY</small><h3>Faites remonter une idée utile à la surface.</h3><p>Publiez, discutez, testez—puis construisez ce qui mérite d'exister.</p></div><button class="kgp-primary">Rejoindre Kogia</button><button>Écrire à Kogia</button></div><footer class="kgp-footer"><b>Kogia Group</b><span>Idées</span><span>Produits</span><span>Communauté</span><span>À propos</span><span>Confidentialité</span><i></i><small>© 2026 · Tunisie & Bahreïn</small></footer>`)
 ].join('');return {shared,brand};
}
